dist: xenial
sudo: false
language: scala

matrix:
  include:
    - jdk: openjdk9
      scala: 0.22.0-bin-20200128-e7a0f80-NIGHTLY
      env: COVERAGE=
    - jdk: openjdk8
      scala: 2.13.0
    # We want the latest stable Scala last so sbt-travisci makes it the default
    - jdk: openjdk8
      scala: 2.12.9
    - jdk: openjdk11
      scala: 2.12.9

install:
  - rvm install 2.6
  # In case we want to reinstall all Ruby dependencies from scratch:
  #   rvm --force gemset delete 2.6@cats-effect
  - rvm use 2.6@cats-effect --default --create
  - bundle install --system --gemfile=site/Gemfile

script:
  - sbt ++$TRAVIS_SCALA_VERSION ci
  - |
    if [[ "$TRAVIS_SCALA_VERSION" =~ ^2\.12\. ]]; then
      sbt ++$TRAVIS_SCALA_VERSION microsite/makeMicrosite
    fi

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
    - $HOME/.rvm
